### ISSUE TITLE
Error on start: Could not resolve placeholder 'oidc.issuer'

### ISSUE THREAD

**Issue by morungos** [morungos/openid-connect-server#5]
Backtrace is: 

```
java.lang.IllegalArgumentException: Could not resolve placeholder 'oidc.issuer' in string value "${oidc.issuer}"
    at org.springframework.beans.factory.config.PlaceholderConfigurerSupport.doProcessProperties(PlaceholderConfigurerSupport.java:209)
    at org.springframework.beans.factory.config.PropertyPlaceholderConfigurer.processProperties(PropertyPlaceholderConfigurer.java:223)
    at org.springframework.beans.factory.config.PropertyResourceConfigurer.postProcessBeanFactory(PropertyResourceConfigurer.java:84)
```

It's basically wrong: we need to inject the oidc.issuer better from outside the war file for the provider.

**Comment by morungos** [comment]
Resolved in d56c2e8
